# Generated by Django 5.2.1 on 2025-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('re_mobile', models.CharField(max_length=20)),
                ('laptop', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('about', models.CharField(max_length=20)),
                ('textarea', models.CharField(max_length=20)),
                ('checkbox', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('ssd', models.CharField(max_length=20)),
                ('youtube_chanel', models.BooleanField()),
            ],
        ),
    ]
